### ISSUE TITLE
Comments in vannila JS oddly formated

### ISSUE THREAD

**Issue by FerreiraRaphael** [madskristensen/JavaScriptPrettier#10]
### Installed product versions
- Visual Studio: Microsoft Visual Basic 2017
- This extension: 1.1.21

### Description
Comments on JS code are being oddly formated

### Steps to recreate
1. Create a comment like this
![image](https://user-images.githubusercontent.com/11987481/27960097-5f2693e0-6300-11e7-9467-7fa858dc1ae7.png)

2. Use preetier to format (Crtl+K + Crtl+J)

### Current behavior
Every time a use preetier to format it add spaces to the comment like:
![image](https://user-images.githubusercontent.com/11987481/27960116-71ecd660-6300-11e7-8465-6e4022981450.png)

And if I format again, the result will be:
![image](https://user-images.githubusercontent.com/11987481/27960131-84013940-6300-11e7-91ee-44567a969305.png)

And so on

### Expected behavior
A normal indentation and format.

**Comment by jesperbjensen** [comment]
This should be fixed by the newest CI version. I will close the issue when a new version is published to the public gallery

**Comment by jesperbjensen** [comment]
Fixed in recent release: https://marketplace.visualstudio.com/items?itemName=MadsKristensen.JavaScriptPrettier
