### ISSUE TITLE
Menu for "Make Prettier" keeps saying "installing npm modules..."

### ISSUE THREAD

**Issue by bitflower** [madskristensen/JavaScriptPrettier#11]
### Installed product versions
- Visual Studio: 2015 Community Update 3
- This extension: 1.1.21

### Description
Menu for prettier keeps saying "Make Prettier (installing npm modules ...)"

### Steps to recreate
1. Install extension through VS dialog
2. Restart VS
3. Menu says above mentioned text
4. Install npm manually npm i prettier --save-dev
5. Restart VS
6. Menu does not change...

### Expected behavior
Menu should switch to "Make prettier" and actually format the code.

![bildschirmfoto 2017-08-02 um 08 20 17](https://user-images.githubusercontent.com/6666636/28860134-77f71088-775b-11e7-8edb-e3c8c4f39a77.png)
![bildschirmfoto 2017-08-02 um 08 21 07](https://user-images.githubusercontent.com/6666636/28860152-8e4d9e1a-775b-11e7-88d7-8222dc7d3b3e.png)
![bildschirmfoto 2017-08-02 um 08 21 34](https://user-images.githubusercontent.com/6666636/28860166-a0be600c-775b-11e7-9d24-3bc71498d74f.png)

**Comment by hmstrand** [comment]
I have the same issue but running VS 2017.  prettier -v = 1.7.4

**Comment by SwannLV** [comment]
Same issue here wit VS2017 15.5.7. Any idea? Thank you very much

**Comment by wayrex** [comment]
You could try and install the prettier package on the extension temporal folder (Windows: C:\users\{userName}\AppData\Local\Temp\Javascript Prettier\{someNumber}\)
By running npm install prettier.
If there's a package-lock or node_modules folder, try removing them before installing it.

**Comment by SwannLV** [comment]
This worked for me. Thanks!
Would you know if there is a way to find this path programmatically? To be able to create a .cmd file that would install prettier there.

**Comment by jesperbjensen** [comment]
This should be fixed by the newest CI version. I will close the issue when a new version is published to the public gallery

**Comment by jesperbjensen** [comment]
Fixed in recent release: https://marketplace.visualstudio.com/items?itemName=MadsKristensen.JavaScriptPrettier
