### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by matelich** [madskristensen/JavaScriptPrettier#13]
### Installed product versions
- Visual Studio: 2017 Professional 15.4.4
- This extension: 1.1.21

### Description
Below is the output I see whenever I open my static website project. It appears I can't upgrade the Node.js that VS uses.

> 11/20/2017 8:20:48 PM: npm install prettier@1.4.2 (this can take a few minutes)
> 11/20/2017 8:20:49 PM: npm WARN npm npm does not support Node.js v5.4.1
> npm WARN npm You should probably upgrade to a newer version of node as we
> npm WARN npm can't make any promises that npm will work with this version.
> npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8.
> npm WARN npm You can find the latest version at https://nodejs.org/
> npm ERR! Buffer.alloc is not a function

### Steps to recreate
1. Configure VS2017 like me
2. Install prettier
3. Weep

### Current behavior
npm is not happy.

### Expected behavior
Successfully make my js pretty.

**Comment by KINGH242** [comment]
I am getting the same error.  

![prettier-error1](https://user-images.githubusercontent.com/876963/34887516-b50e55f6-f7be-11e7-8b4c-351dd4ae2c8d.png)

![prettier-error2](https://user-images.githubusercontent.com/876963/34887484-98094cfe-f7be-11e7-8e53-87b3ee190d2b.png)

**Comment by SwannLV** [comment]
Hello, have you found any solution or workaround to run prettier in vs2017?

Thank you :)

**Comment by achebrol** [comment]
you can install the prettier manually at this location
C:\Users\<<username>>\AppData\Local\Microsoft\VisualStudio\15.0_f1aee8cf\Extensions\bdqsagnf.dxh
check the full path. it will be different on your machine based on the hashcode
but i am still trying to figure out how to add come configuration using .prettierrc

**Comment by SwannLV** [comment]
Hello,
Thank you very much but it still doesn't work. I have installed the prettier@1.4.2 manually at C:\Users\myname\AppData\Local\Microsoft\VisualStudio\15.0_22f082bf\Extensions\4auxeyxe.iof
where prettier is and restarted. I still have the installing npm modules message again.

If I can arrange some time, I will try to debug that and let you know.
Thanks

**Comment by SwannLV** [comment]
The extension is installing prettier@1.4.2 into C:\Users\myname\ directory

**Comment by achebrol** [comment]
you can install latest version which installs prettier@1.8.2 from here
https://github.com/madskristensen/JavaScriptPrettier/pull/15#issuecomment-348536660
I was having issue with our internet proxy and manually installing the package ,did solve the problem.

**Comment by jesperbjensen** [comment]
This should be fixed by the newest CI version. I will close the issue when a new version is published to the public gallery

**Comment by jesperbjensen** [comment]
Fixed in recent release: https://marketplace.visualstudio.com/items?itemName=MadsKristensen.JavaScriptPrettier
