### ISSUE TITLE
How to configure .prettierrc?

### ISSUE THREAD

**Issue by djm158** [madskristensen/JavaScriptPrettier#18]
### Installed product versions
- Visual Studio: 2017 Enterprise 15.6.4
- This extension: 1.1.21

### Description
Where does this extension read a `.prettierrc` from?

### Steps to recreate
1. Create .prettierrc (in top level of project, for example)
2. Run "Make Prettier"

### Current behavior
Does not read config from `.prettierrc`

### Expected behavior
Read config from `.prettierrc` and format accordingly.

**Comment by djm158** [comment]
I was able to get this to work by installing http://vsixgallery.com/extension/J1da7ad9e-85b3-4a0c-8e45-b2ae59a575a7/ and putting a `.prettierrc` in the top level of my project directory. I assume the next release to the marketplace will include this?

**Comment by jesperbjensen** [comment]
Hi @djm158 

Yes - the next version will be the same as the newest CI build (it has just been updated with a newer Prettier version today)

I will close your issue then the new public build hits the marketplace - and I have updated the documentation with some more help about configuring.

**Comment by jesperbjensen** [comment]
Fixed in recent release: https://marketplace.visualstudio.com/items?itemName=MadsKristensen.JavaScriptPrettier
