### ISSUE TITLE
Unable to install the extension on VS Code

### ISSUE THREAD

**Issue by margozzi** [madskristensen/JavaScriptPrettier#27]
### Installed product versions
- Visual Studio: 1.36.1
- This extension: 2.1.47

### Description
I am unable to install the extension.

### Steps to recreate
Download extension  "JavaScript_Prettier_v2.1.47.vsix" 
Use VS Code UI or cammand line to try and install
Get error message: "extension/package.json not found inside zip."

### Current behavior
Fails to install, complains of missing json file

### Expected behavior
Install and work without error messages.

**Comment by jesperbjensen** [comment]
This extension is for the original Visual Studio for Windows

If you are using Visual Studio Code then this is the extension you need: https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

It’s confusing - I know...

I hope it helps you. Prettier is awesome - and the VS Code extension is best in class.

**Comment by margozzi** [comment]
You are amazing my friend!  Thank you for the quick response. I look forward to enjoying this extension :-)
