### ISSUE TITLE
Visual studio 2017 command group ID does not match

### ISSUE THREAD

**Issue by ripvannwinkler** [madskristensen/JavaScriptPrettier#3]
### Installed product versions
- Visual Studio: 2017 Professional RTM
- This extension: 0.6

### Description
Right click menu always reads "Make Prettier (installing npm modules...)"

### Steps to recreate
1. Install extension to Visual Studio 2017 RTM
2. Open VS and open a javascript file
3. Right click the document

### Current behavior
Context menu item reads "Make Prettier (installing npm modules...)"

### Expected behavior
The make prettier option should be available

I have downloaded a fork of the source and found the issue to be with line 73 of PrettierCommand.cs which reads:

    if (pguidCmdGroup == _commandGroup && prgCmds[0].cmdID == _commandId)

However, the value of pguidCmdGroup is `{60120aad-4139-4f1c-a5b3-d0c68fff2511}` while the value of _commandGroup is `{1adbe5b8-de7d-446c-85d6-c1c121aacff3}`. Because of this, the inside block that sets the appropriate status never runs.

I would update and submit a pull request, but I'm unsure why the mismatch occurs nor what the correct value should be for VS 2017 RTM.

Edit: I have verified that the code that installs the NPM module returns successfully. However, when I check `C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External\node_modules`, the module does not exist. I do have the module installed globally, so that may be affecting the install. Regardless, the issue appears to step from the command group ID check noted above.

**Comment by jesperbjensen** [comment]
This should be fixed by the newest CI version. I will close the issue when a new version is published to the public gallery

**Comment by jesperbjensen** [comment]
Fixed in recent release: https://marketplace.visualstudio.com/items?itemName=MadsKristensen.JavaScriptPrettier
