### ISSUE TITLE
Prettier not installing on macOS 12.0

### ISSUE THREAD

**Issue by shriraj20** [madskristensen/JavaScriptPrettier#40]
### Installed product versions
- Webstorm: 2021.3
- This extension: prettier 2.5.1

### Description
<img width="1440" alt="Screen Shot 2021-12-24 at 6 58 57 PM" src="https://user-images.githubusercontent.com/59427722/147376443-b672fccd-97fa-422b-b476-588a1ec6928c.png">

### Steps to recreate
1. Reinstall node
2. Tried Intelij webstorm plugin
3. uninstalled plugin and used node edition
4. uninstalled plugin and used node

**Comment by HolgerJeromin** [comment]
This repo is for the Visual Studio extension not prettier itself.
