### ISSUE TITLE
Editor scrolls to bottom when format large file using prettier

### ISSUE THREAD

**Issue by ghost** [madskristensen/JavaScriptPrettier#41]
In vscode running the `editor.action.formatDocument` command in a javascript file makes the editor scroll to the last line of the file which is really annoying. It happens for large files that are 6000+ lines. It tends to happen when the content of the line the cursor is on changes due to being formatted.

I've disabled all extensions apart from prettier and it's still happening. I also set up a new codespace and installed prettier and no other extensions and it happens in there.

**Comment by HolgerJeromin** [comment]
This extension is no vscode extension! This is for Visual Studio 2019.
Your bug report here is at the wrong place.
