### ISSUE TITLE
Knockout observable properties are formatted wrong

### ISSUE THREAD

**Issue by nwinger** [madskristensen/JavaScriptPrettier#8]
### Installed product versions
- Visual Studio: 2017 Enterprise
- JavaScript Prettier 1.1.21

### Description
Formatting of model properties of type ko.observable<boolean> are formatted wrong, causing code errors.

### Steps to recreate
Create a class containing a knockout based boolean property

### Current behavior
`closeButtonVisible = ko.observable < boolean > false;`
Causing the following code to be invalid: `vm.closeButtonVisible(true);`

`Cannot invoke an expression whose type lacks a call signature. Type 'Boolean' has no compatible call signatures-`

### Expected behavior
`closeButtonVisible = ko.observable<boolean>(false);`

**Comment by madskristensen** [comment]
Can you please open the issue on the Prettier repo, since this extension just calls it https://github.com/prettier/prettier

**Comment by nwinger** [comment]
@madskristensen Tried it in VSCode with the latest version just for kicks. Not the same behaviour. Do you depend on different versions?

**Comment by jesperbjensen** [comment]
Hi @nwinger 

The newest CI build updates Prettier to the latest version. It should fix the issue. I will close the issue when a new version is published to the public gallery

**Comment by jesperbjensen** [comment]
Fixed in recent release: https://marketplace.visualstudio.com/items?itemName=MadsKristensen.JavaScriptPrettier
