### ISSUE TITLE
Not Available in Visual Studio 2015

### ISSUE THREAD

**Issue by farzadmf** [madskristensen/JavaScriptPrettier#9]
### Installed product versions
- Visual Studio: Visual Studio 2015 Enterprise
- This extension: 1.1.21

### Description
Not available in JavaScript files

### Steps to recreate
I am not sure whether I am missing something, but I installed the extension, and I don't see anything in the context menu to run it when I am in a `.js` file

### Current behavior
No way to use the extension

### Expected behavior
I should see the option to be able to run

**Comment by tommck** [comment]
Should probably close this, since it's OLD and not getting responses
